group: trusty_lts
language: java
jdk:
  - openjdk8
  - oraclejdk8
install: true
script:
  - bash gradlew clean build asciidoctor
  - export ROOT=$PWD
  - >
    for path in \
      grails-react \
      grails-angular \
      grails-angularjs \
    ;
    do
      export TARGET="$ROOT/$path"
      cd $TARGET
      bash gradlew clean build
    done
