group: edge
dist: trusty

language: java
jdk:
  - openjdk8
  - oraclejdk8

install: true

script:
  - bash gradlew clean build
  - export ROOT=$PWD
  - >
    for path in \
      grails-react \
      grails-angular \
    ;
    do
      export TARGET="$ROOT/$path"
      cd $TARGET
      bash gradlew clean build
    done

before_cache:
  - bash gradlew --stop
  - rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.m2/
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
